// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/ZkAceVerifier.sol";
import "../src/ZkAceAccount.sol";
import "../src/IZkAceVerifier.sol";
import "account-abstraction/interfaces/IEntryPoint.sol";
import "account-abstraction/interfaces/PackedUserOperation.sol";
import "account-abstraction/core/EntryPoint.sol";

/// @title End-to-End Integration Test
/// @notice Tests the complete ZK-ACE flow with REAL Groth16 proofs
///         generated by the Rust prover and verified through the
///         generated Solidity verifier contract.
///
/// This test proves: a quantum-resistant identity (derived from a
/// 256-bit Root Entropy Value) can authorize EVM transactions via
/// zero-knowledge proofs — no ECDSA keys involved.
contract E2ETest is Test {
    // ---- Contracts ----
    EntryPoint entryPoint;
    ZkAceVerifier verifier;
    ZkAceAccount account;
    address payable beneficiary = payable(address(0xBEEFCAFE));

    // ---- Fixture data generated by Rust prover (gen_fixture binary) ----
    // These values are the output of: cargo run -p zk-ace-prover --bin gen_fixture
    //
    // Identity: REV = random 256-bit value (never revealed on-chain)
    // Commitment: IDcom = Poseidon(REV, salt, domain)
    // The only thing stored on-chain is the 32-byte IDcom.
    // The proof demonstrates knowledge of REV without revealing it.

    bytes32 constant ID_COM = 0x1ef24cd71b7ec7398964d35ba7474fe89c109b26ed9cda4ba39599bef3177f4c;

    // Groth16 proof (A, B, C group elements) — generated with PRODUCTION proving key
    uint256[2] proofA = [
        0x25d5a378332839f4adbaa22b9910ad6c65089d9eb370947658a0c187a8767f7d,
        0x18961f80fa2d391b84c20f2bb05ddb0b5b1bc0993242355c63fc174e9ac5b153
    ];
    uint256[2][2] proofB = [
        [
            0x027bebe168c94add771a27448b7b21920891b8ca50dedc00a63496823cf736c6,
            0x05d0be27e78704fb8d349d735443ad502cfdca3c10b6d79bb9705461185ad532
        ],
        [
            0x19bbd59aefd42104540fa6840c71691eb1b5127ad043acafbcefaac61f0232cf,
            0x034973ecf897be0cf18f77819798b1d486dd3e3041fd399791eb46327cdbe777
        ]
    ];
    uint256[2] proofC = [
        0x13184cb6a794f406b40ba9ada473b221027e84420ea6841a5c5bbb2617ae7a71,
        0x0e07df6dd63a2426affc3b3063c676638db3510a9e3a7aefb8539c38607c1d5d
    ];

    // Public inputs: [IDcom, TxHash, domain, target, rpCom]
    uint256[5] publicInputs = [
        0x1ef24cd71b7ec7398964d35ba7474fe89c109b26ed9cda4ba39599bef3177f4c,
        0x07577d7259c5e8f76ba7fcb065102c4efb4b9511228e5aa135837d961eca80dc,
        0x0000000000000000000000000000000000000000000000000000000000007a69,
        0x1b83658b970a31c979bba666cdf22bf7b4bb42fdc520f954babf809a4983fb63,
        0x034159f1c697cb958dfd78417296b81b96d4308c47cc574c46467f8e08fc6675
    ];

    // The calldata this proof authorizes (execute: send 0.001 ETH to 0xdead)
    bytes constant AUTHORIZED_CALLDATA = hex"b61d27f6000000000000000000000000000000000000000000000000000000000000dead00000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000";

    uint256 constant BN254_FR_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function setUp() public {
        // Deploy the real EntryPoint
        entryPoint = new EntryPoint();

        // Deploy the REAL generated Groth16 verifier (not a mock!)
        verifier = new ZkAceVerifier();

        // Deploy ZK-ACE account with real verifier
        // Chain ID 31337 matches Anvil default and the proof's domain
        account = new ZkAceAccount(
            IEntryPoint(address(entryPoint)),
            IZkAceVerifier(address(verifier)),
            ID_COM
        );

        // Fund the account with 10 ETH (it's a vault!)
        vm.deal(address(account), 10 ether);

        // Deposit to EntryPoint for gas
        vm.deal(address(this), 10 ether);
        entryPoint.depositTo{value: 5 ether}(address(account));
    }

    // ============================================================
    //  TEST 1: Groth16 proof verifies through the REAL Solidity verifier
    // ============================================================
    function test_realGroth16ProofVerifiesOnChain() public view {
        bool valid = verifier.verifyProof(proofA, proofB, proofC, publicInputs);
        assertTrue(valid, "Real Groth16 proof must verify on-chain");
    }

    // ============================================================
    //  TEST 2: Mutated proof FAILS on-chain (soundness check)
    // ============================================================
    function test_mutatedProofFailsOnChain() public {
        // Mutating a G1 point coordinate may produce an invalid curve point,
        // which causes the BN254 precompile to revert (not return false).
        // Either outcome (false or revert) is correct — the proof is rejected.
        uint256[5] memory badInputs = publicInputs;
        badInputs[0] = badInputs[0] + 1; // Wrong IDcom
        // This keeps points valid but changes the statement being proved
        try verifier.verifyProof(proofA, proofB, proofC, badInputs) returns (bool valid) {
            assertFalse(valid, "Mutated inputs must fail verification");
        } catch {
            // Revert is also acceptable — proof is rejected
            assertTrue(true);
        }
    }

    // ============================================================
    //  TEST 3: Wrong public inputs FAIL (prevents substitution attack)
    // ============================================================
    function test_wrongPublicInputsFailOnChain() public view {
        uint256[5] memory badInputs = publicInputs;
        badInputs[1] = 0xDEAD; // Wrong TxHash
        bool valid = verifier.verifyProof(proofA, proofB, proofC, badInputs);
        assertFalse(valid, "Wrong public inputs must fail");
    }

    // ============================================================
    //  TEST 4: TxHash recomputation prevents public-input malleability
    // ============================================================
    function test_txHashRecomputationMatchesProof() public view {
        // The contract recomputes TxHash from calldata
        uint256 recomputed = uint256(keccak256(AUTHORIZED_CALLDATA)) % BN254_FR_MODULUS;
        assertEq(
            recomputed,
            publicInputs[1],
            "On-chain TxHash recomputation must match the proof's TxHash"
        );
    }

    // ============================================================
    //  TEST 5: Full validation + execution with real verifier
    // ============================================================
    function test_fullUserOpFlowWithRealProof() public {
        // Build the signature: ABI-encode proof + pubInputs + nonce
        bytes memory sig = abi.encode(
            proofA, proofB, proofC, publicInputs
        );

        // Build the UserOperation
        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.nonce = 0;
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        // Step 1: Validate the UserOp (as the EntryPoint would)
        // This exercises the full ZK-ACE validation path:
        //   TxHash recomputation → IDcom check → domain check → Groth16 verify → nonce advance
        vm.prank(address(entryPoint));
        uint256 validationData = account.validateUserOp(userOp, bytes32(0), 0);
        assertEq(validationData, 0, "SIG_VALIDATION_SUCCESS: ZK-ACE proof must validate");

        // Step 2: Execute the authorized transaction (as the EntryPoint would)
        vm.prank(address(entryPoint));
        account.execute(
            address(0xdead),
            0.001 ether,
            ""
        );

        // Step 3: Verify state changes
        assertEq(address(0xdead).balance, 0.001 ether, "Target should receive 0.001 ETH");
        assertEq(account.zkNonce(), 1, "Nonce should advance to 1");
    }

    // ============================================================
    //  TEST 6: Nonce advances on each valid proof (replay prevention
    //           is enforced at the circuit level via rp_com = H(idCom, nonce))
    // ============================================================
    function test_nonceAdvancesOnValidation() public {
        bytes memory sig = abi.encode(
            proofA, proofB, proofC, publicInputs
        );

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        assertEq(account.zkNonce(), 0, "Nonce starts at 0");

        // Validation succeeds and nonce advances
        vm.prank(address(entryPoint));
        uint256 result = account.validateUserOp(userOp, bytes32(0), 0);
        assertEq(result, 0, "Validation should succeed");
        assertEq(account.zkNonce(), 1, "Nonce advanced to 1 after valid proof");
    }

    // ============================================================
    //  TEST 7: Cross-chain replay protection (domain separation)
    // ============================================================
    function test_crossChainReplayProtection() public {
        // The proof was generated for chain ID 31337
        assertEq(account.domainTag(), 31337, "Domain tag should match Anvil chain ID");
        assertEq(publicInputs[2], 31337, "Proof domain should match chain ID");

        // If we somehow deployed on a different chain, domain check would fail
        // We can test this by deploying a new account with a different domain expectation
        // and trying to use the same proof

        // Deploy account expecting a different chain (this simulates wrong chain)
        vm.chainId(1); // Pretend we're on mainnet
        ZkAceAccount wrongChainAccount = new ZkAceAccount(
            IEntryPoint(address(entryPoint)),
            IZkAceVerifier(address(verifier)),
            ID_COM
        );
        vm.chainId(31337); // Reset

        // The account's domainTag was set to 1 (mainnet) at construction
        assertEq(wrongChainAccount.domainTag(), 1);

        bytes memory sig = abi.encode(
            proofA, proofB, proofC, publicInputs
        );

        PackedUserOperation memory userOp;
        userOp.sender = address(wrongChainAccount);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.accountGasLimits = bytes32(uint256(2_000_000) << 128 | uint256(200_000));
        userOp.preVerificationGas = 100_000;
        userOp.gasFees = bytes32(uint256(1 gwei) << 128 | uint256(10 gwei));
        userOp.signature = sig;

        // This should fail because proof domain (31337) != account domain (1)
        vm.deal(address(wrongChainAccount), 10 ether);
        entryPoint.depositTo{value: 5 ether}(address(wrongChainAccount));

        // Validate — should fail because proof domain (31337) != account domain (1)
        vm.prank(address(entryPoint));
        vm.expectRevert(); // DomainMismatch
        wrongChainAccount.validateUserOp(userOp, bytes32(0), 0);
    }

    // ============================================================
    //  TEST 8: Identity binding — proof for one wallet cannot be
    //           used on a different wallet (different IDcom)
    // ============================================================
    function test_identityBindingPreventsWrongWallet() public {
        // Deploy another account with a DIFFERENT identity commitment
        bytes32 otherIdCom = bytes32(uint256(0xBEEF));
        ZkAceAccount otherAccount = new ZkAceAccount(
            IEntryPoint(address(entryPoint)),
            IZkAceVerifier(address(verifier)),
            otherIdCom
        );

        bytes memory sig = abi.encode(
            proofA, proofB, proofC, publicInputs
        );

        PackedUserOperation memory userOp;
        userOp.sender = address(otherAccount);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        // Try to use our proof on the other account — IDcom mismatch
        vm.prank(address(entryPoint));
        vm.expectRevert(); // IdComMismatch
        otherAccount.validateUserOp(userOp, bytes32(0), 0);
    }

    // ============================================================
    //  TEST 9: Transaction substitution attack — proof cannot be
    //           used for different calldata (different transaction)
    // ============================================================
    function test_transactionSubstitutionAttack() public {
        // Different calldata: try to drain all funds instead
        bytes memory maliciousCalldata = abi.encodeWithSelector(
            bytes4(0xb61d27f6), // execute(address,uint256,bytes)
            address(0xE7E), // attacker address
            address(account).balance, // steal everything
            ""
        );

        bytes memory sig = abi.encode(
            proofA, proofB, proofC, publicInputs
        );

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = maliciousCalldata; // Different from what proof authorizes!
        userOp.signature = sig;

        // TxHash recomputed from malicious calldata won't match proof's TxHash
        vm.prank(address(entryPoint));
        vm.expectRevert(); // TxHashMismatch
        account.validateUserOp(userOp, bytes32(0), 0);
    }

    // Helper to receive ETH (from EntryPoint refunds)
    receive() external payable {}
}
