// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/ZkAceVerifier.sol";
import "../src/ZkAceAccount.sol";
import "../src/IZkAceVerifier.sol";
import "account-abstraction/interfaces/IEntryPoint.sol";
import "account-abstraction/interfaces/PackedUserOperation.sol";
import "account-abstraction/core/EntryPoint.sol";

/// @title E2E on Arbitrum One MAINNET
/// @notice Tests the ZK-ACE flow with production proof data for chain 42161.
///         Run with: forge test --match-contract E2E_ArbitrumMainnet --fork-url https://arb1.arbitrum.io/rpc -vvv
contract E2E_ArbitrumMainnetTest is Test {
    EntryPoint entryPoint;
    ZkAceVerifier verifier;
    ZkAceAccount account;

    bytes32 constant ID_COM = 0x2cee598f7976e2d1f3ad7a1f66c38a0294a9e657f899ae052724a9f79b96b098;

    // Proof generated by Rust prover for chain 42161 — PRODUCTION proving key
    uint256[2] proofA = [
        0x1b0daacfe04245298ea75e3a4d9fc3af7f229900b9286b7b9bbb40ab57fac1c4,
        0x2e4798ca88a1fe5f3e12d7be82073abf5eb0a19cfdb3410a416f62818ac106ac
    ];
    uint256[2][2] proofB = [
        [
            0x090bc2676d1e10e832d49d896ae3dedfaec68ef4524833418d9955f0dbd21e9b,
            0x1a2a236eae0e5da3499033ae706fb5a12262f09b9434783fce96bec37d876bb9
        ],
        [
            0x25abf816c80398cd364da579b8866c34792d9ea616a8178f81187100b480b83a,
            0x05f988151f530113172323fa66b016e638342ea432725f29f63ceab041036605
        ]
    ];
    uint256[2] proofC = [
        0x02dbb1ba53bfd44963ddaeb16a22d848a79888ad56e24cb3a66a5c1ee408ffe9,
        0x2702afb799c2410f5eec135202624fdd2850edc5710d62bcfc8efaced610c626
    ];

    uint256[5] publicInputs = [
        0x2cee598f7976e2d1f3ad7a1f66c38a0294a9e657f899ae052724a9f79b96b098,
        0x07577d7259c5e8f76ba7fcb065102c4efb4b9511228e5aa135837d961eca80dc,
        0x000000000000000000000000000000000000000000000000000000000000a4b1,
        0x05dca9418828d66818f82360798ed9fb948eaec88927ffb1b44cb17b3da368f2,
        0x265d61013e4f2f3e8cbc184da16ca3d27ab2e5144b6fd0582ffc15ae7f57f1df
    ];

    // execute(address,uint256,bytes) — send 0.001 ETH to 0xdead
    bytes constant AUTHORIZED_CALLDATA = hex"b61d27f6000000000000000000000000000000000000000000000000000000000000dead00000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000";

    uint256 constant BN254_FR_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function setUp() public {
        vm.skip(block.chainid != 42161);
        entryPoint = new EntryPoint();
        verifier = new ZkAceVerifier();
        account = new ZkAceAccount(
            IEntryPoint(address(entryPoint)),
            IZkAceVerifier(address(verifier)),
            ID_COM
        );
        vm.deal(address(account), 1 ether);
    }

    function test_contractsDeployedOnMainnet() public view {
        assertTrue(address(verifier).code.length > 0, "Verifier live on Arbitrum One");
        assertTrue(address(account).code.length > 0, "ZkAceAccount live on Arbitrum One");
    }

    function test_vaultConfigCorrect() public view {
        assertEq(account.idCom(), ID_COM, "IDcom matches");
        assertEq(account.domainTag(), 42161, "Domain tag is Arbitrum One");
        assertEq(address(account.verifier()), address(verifier), "Verifier linked");
        assertEq(account.zkNonce(), 0, "Nonce starts at 0");
    }

    function test_proofVerifiesOnArbitrumMainnet() public view {
        bool valid = verifier.verifyProof(proofA, proofB, proofC, publicInputs);
        assertTrue(valid, "Groth16 proof verified on REAL Arbitrum One");
    }

    function test_txHashMatchesOnMainnet() public view {
        uint256 recomputed = uint256(keccak256(AUTHORIZED_CALLDATA)) % BN254_FR_MODULUS;
        assertEq(recomputed, publicInputs[1], "TxHash matches");
    }

    function test_fullValidationAndExecution() public {
        bytes memory sig = abi.encode(proofA, proofB, proofC, publicInputs);

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        // Validate as EntryPoint
        vm.prank(address(entryPoint));
        uint256 result = account.validateUserOp(userOp, bytes32(0), 0);
        assertEq(result, 0, "SIG_VALIDATION_SUCCESS on Arbitrum One mainnet");

        // Nonce consumed
        assertEq(account.zkNonce(), 1, "Nonce advanced to 1");

        // Execute the authorized transfer
        uint256 deadBefore = address(0xdead).balance;

        vm.prank(address(entryPoint));
        account.execute(address(0xdead), 0.001 ether, "");

        assertEq(
            address(0xdead).balance,
            deadBefore + 0.001 ether,
            "0xdead received 0.001 ETH via quantum-resistant proof on Arbitrum One"
        );
    }

    function test_nonceAdvancesOnMainnet() public {
        bytes memory sig = abi.encode(proofA, proofB, proofC, publicInputs);

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        assertEq(account.zkNonce(), 0, "Nonce starts at 0");

        vm.prank(address(entryPoint));
        account.validateUserOp(userOp, bytes32(0), 0);

        assertEq(account.zkNonce(), 1, "Nonce advanced to 1");
    }
}
