// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/ZkAceVerifier.sol";
import "../src/ZkAceAccount.sol";

import "../src/IZkAceVerifier.sol";
import "account-abstraction/interfaces/IEntryPoint.sol";
import "account-abstraction/interfaces/PackedUserOperation.sol";
import "account-abstraction/core/EntryPoint.sol";

/// @title E2E Integration Test for Arbitrum Sepolia (chain 421614)
/// @notice Proves that a quantum-resistant ZK-ACE vault works on Arbitrum's real EVM.
///         Run with: forge test --match-contract E2E_Arbitrum --fork-url https://sepolia-rollup.arbitrum.io/rpc -vvv
contract E2E_ArbitrumTest is Test {
    EntryPoint entryPoint;
    ZkAceVerifier verifier;
    ZkAceAccount account;

    uint256 constant BN254_FR_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ---- Fixture: proof generated by Rust prover for chain ID 421614 (Arbitrum Sepolia) ----
    bytes32 constant ID_COM = 0x07d318092b04b29a30d2a36cfa6219caa37441d1061746fa969c559486cbcbb9;

    uint256[2] proofA = [
        0x28116c84bc33ef2515108861a80ed8b69e0ee53674e445d021d09f8a0ba681bc,
        0x2d2cdb72526bd542c9f5d93ac01a552ae99f146c98f8cfb96b2c0320f030596b
    ];
    uint256[2][2] proofB = [
        [
            0x2f18e68d59c1aab999645a2eaac6e53d7b66cf6a04f1861667a46c1fc516d1f9,
            0x041418303aaa0270d49150f66df462a8502e815c39ccf17109d49624aaa46335
        ],
        [
            0x205a737181838259ef4c54dd9db4d8d40c7e604a5fbd8ddd1f342067fbdb38f8,
            0x2d886bd9148979eb40b7d2b52a1a4d301b7c6ea0d09eab804fc0e4fd4cd7eccc
        ]
    ];
    uint256[2] proofC = [
        0x09e10cdd25a4ac211ec0670097f5d991c65180136594bf3c81b6314a9874ee4b,
        0x2e663036cc59f7b636a2fc11cd0f2c7f785631790d2c783781f69b8825af42f4
    ];

    uint256[5] publicInputs = [
        0x07d318092b04b29a30d2a36cfa6219caa37441d1061746fa969c559486cbcbb9, // IDcom
        0x07577d7259c5e8f76ba7fcb065102c4efb4b9511228e5aa135837d961eca80dc, // TxHash
        0x0000000000000000000000000000000000000000000000000000000000066eee, // domain = 421614
        0x224718cde00795d3c0b91ea78caa4082fe90771bc44278fb6507bf005edbd762, // target
        0x25928bd46041d917e04dc177734e35be77b21b82c89e717bfd68e2894764010c  // rpCom
    ];

    // execute(address,uint256,bytes) — send 0.001 ETH to 0xdead
    bytes constant AUTHORIZED_CALLDATA = hex"b61d27f6000000000000000000000000000000000000000000000000000000000000dead00000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000";

    function setUp() public {
        // Skip if not on Arbitrum Sepolia fork
        vm.skip(block.chainid != 421614);

        entryPoint = new EntryPoint();
        verifier = new ZkAceVerifier();
        account = new ZkAceAccount(
            IEntryPoint(address(entryPoint)),
            IZkAceVerifier(address(verifier)),
            ID_COM
        );
        vm.deal(address(account), 1 ether);
    }

    /// @notice Groth16 proof verifies on Arbitrum Sepolia's real BN254 precompiles
    function test_proofVerifiesOnArbitrum() public view {
        bool valid = verifier.verifyProof(proofA, proofB, proofC, publicInputs);
        assertTrue(valid, "Groth16 proof must verify on Arbitrum");
    }

    /// @notice TxHash matches the proof's domain-bound transaction hash
    function test_txHashMatchesOnArbitrum() public view {
        uint256 recomputed = uint256(keccak256(AUTHORIZED_CALLDATA)) % BN254_FR_MODULUS;
        assertEq(recomputed, publicInputs[1], "TxHash must match on Arbitrum");
    }

    /// @notice Domain tag matches Arbitrum Sepolia chain ID
    function test_domainMatchesArbitrum() public view {
        assertEq(account.domainTag(), 421614);
        assertEq(publicInputs[2], 421614);
    }

    /// @notice Full ZK-ACE validation + execution on Arbitrum
    function test_fullFlowOnArbitrum() public {
        bytes memory sig = abi.encode(proofA, proofB, proofC, publicInputs);

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        // Validate — full ZK-ACE path with real Groth16 verification
        vm.prank(address(entryPoint));
        uint256 result = account.validateUserOp(userOp, bytes32(0), 0);
        assertEq(result, 0, "SIG_VALIDATION_SUCCESS on Arbitrum");

        // Execute the authorized ETH transfer
        uint256 deadBefore = address(0xdead).balance;
        vm.prank(address(entryPoint));
        account.execute(address(0xdead), 0.001 ether, "");

        assertEq(address(0xdead).balance, deadBefore + 0.001 ether, "0xdead received 0.001 ETH on Arbitrum");
        assertEq(account.zkNonce(), 1, "Nonce advanced");
    }

    /// @notice Nonce advances on Arbitrum (replay prevention via circuit rp_com)
    function test_nonceAdvancesOnArbitrum() public {
        bytes memory sig = abi.encode(proofA, proofB, proofC, publicInputs);

        PackedUserOperation memory userOp;
        userOp.sender = address(account);
        userOp.callData = AUTHORIZED_CALLDATA;
        userOp.signature = sig;

        assertEq(account.zkNonce(), 0, "Nonce starts at 0");

        vm.prank(address(entryPoint));
        account.validateUserOp(userOp, bytes32(0), 0);

        assertEq(account.zkNonce(), 1, "Nonce advanced to 1");
    }
}
