// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/StarkVerifier.sol";

/// @title STARK E2E Test — Real Winterfell proof verified on-chain
/// @notice Uses FFI to load a real STARK proof generated by the Rust prover,
///         then verifies it through the complete Solidity StarkVerifier.
/// @dev Fixture regenerated for 18-col AIR with 256-bit commitments.
contract StarkE2ETest is Test {
    StarkVerifier verifier;

    // Layout: id_com[4] + target[4] + rp_com[4] + domain[1] + tx_hash[4] = 17
            uint64[17] pubInputs = [
        uint64(4921142741371514199),  // id_com[0]
        uint64(3190918489393779307),  // id_com[1]
        uint64(7313801271506381131),  // id_com[2]
        uint64(6142490038807738031),  // id_com[3]
        uint64(16081478264331554156),  // target[0]
        uint64(13237335551400322149),  // target[1]
        uint64(6969670316049965432),  // target[2]
        uint64(11266332307889743866),  // target[3]
        uint64(11560247129149436507),  // rp_com[0]
        uint64(6552210567723423124),  // rp_com[1]
        uint64(15438288165507772353),  // rp_com[2]
        uint64(65933857680088743),  // rp_com[3]
        uint64(42161),  // domain
        uint64(43690),  // tx_hash[0]
        uint64(48059),  // tx_hash[1]
        uint64(52428),  // tx_hash[2]
        uint64(56797)  // tx_hash[3]
    ];

    function setUp() public {
        verifier = new StarkVerifier();
    }

    function _loadProof() internal view returns (bytes memory) {
        string memory hexStr = vm.readFile("contracts/test/fixtures/stark_proof.hex");
        return vm.parseBytes(hexStr);
    }

    function test_realStarkProofVerifies() public {
        bytes memory proof = _loadProof();
        emit log_named_uint("Proof size (bytes)", proof.length);

        bool result = verifier.verifyProof(proof, pubInputs);
        assertTrue(result, "Real STARK proof must verify on-chain");
    }

    function test_realStarkProofGas() public {
        bytes memory proof = _loadProof();
        uint256 gasBefore = gasleft();
        verifier.verifyProof(proof, pubInputs);
        uint256 gasUsed = gasBefore - gasleft();
        emit log_named_uint("STARK E2E verification gas", gasUsed);
        // Should be under 1M for Arbitrum viability
        assertTrue(gasUsed < 10_000_000, "Gas must be under 10M");
    }

    function test_tamperedProofRejected() public {
        bytes memory proof = _loadProof();
        // Tamper with the trace root (byte 0)
        proof[0] = bytes1(uint8(proof[0]) ^ 0xFF);
        // This changes the Fiat-Shamir transcript → grinding fails
        vm.expectRevert(StarkVerifier.GrindingFailed.selector);
        verifier.verifyProof(proof, pubInputs);
    }

    function test_wrongPublicInputsRejected() public {
        bytes memory proof = _loadProof();
        uint64[17] memory badInputs = pubInputs;
        badInputs[0] = 0xDEAD;
        vm.expectRevert(StarkVerifier.GrindingFailed.selector);
        verifier.verifyProof(proof, badInputs);
    }

    function test_numQZeroRejected() public {
        // Audit v3 CRIT-2: numQ=0 should be rejected, not bypass all checks
        bytes memory proof = _loadProof();
        // Overwrite numQ at offset 6816 with 0
        assembly {
            mstore(add(add(proof, 0x20), 6816), 0)
        }
        vm.expectRevert(StarkVerifier.QueryCountInvalid.selector);
        verifier.verifyProof(proof, pubInputs);
    }

    function test_numQTooLargeRejected() public {
        bytes memory proof = _loadProof();
        // Overwrite numQ with 999
        assembly {
            mstore(add(add(proof, 0x20), 6816), 999)
        }
        vm.expectRevert(StarkVerifier.QueryCountInvalid.selector);
        verifier.verifyProof(proof, pubInputs);
    }
}
