// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/StarkVerifier.sol";
import "../src/GoldilocksField.sol";

/// @title StarkVerifier V2 Tests
/// @notice Tests using real fixture data from the Rust STARK prover.
///         The canonical Solidity fixture is generated by the repo's STARK proof-generation flow
///         and checked in under `contracts/test/fixtures/`.
contract StarkVerifierV2Test is Test {
    StarkVerifier verifier;

    uint256 constant P = 18446744069414584321;

    // Fixture data from Rust prover
    bytes32 constant TRACE_ROOT = 0x4de49591f9b63c37e7894a62832320021429c2343386b7169a61a1c8eaf41d00;
    bytes32 constant CONSTRAINT_ROOT = 0xa59ee8734e32815317280367945ca05790eacf3b5224f343243b09a9f1749827;
    bytes32 constant FRI_ROOT = 0xb55af0bca459c4558c51449a07cfd094f2eecac1d57ee5919eacf8f049663bfd;
    bytes32 constant OOD_DIGEST = 0xb2ab49b1f91a0d27afa8e4c0346c9f45ab5f7256c5c1d30901f86f896fcc6358;
    uint64 constant POW_NONCE = 490901;

    // Layout: id_com[4] + target[4] + rp_com[4] + domain[1] + tx_hash[4] = 17
            uint64[17] pubInputs = [
        uint64(4921142741371514199),  // id_com[0]
        uint64(3190918489393779307),  // id_com[1]
        uint64(7313801271506381131),  // id_com[2]
        uint64(6142490038807738031),  // id_com[3]
        uint64(16081478264331554156),  // target[0]
        uint64(13237335551400322149),  // target[1]
        uint64(6969670316049965432),  // target[2]
        uint64(11266332307889743866),  // target[3]
        uint64(11560247129149436507),  // rp_com[0]
        uint64(6552210567723423124),  // rp_com[1]
        uint64(15438288165507772353),  // rp_com[2]
        uint64(65933857680088743),  // rp_com[3]
        uint64(42161),  // domain
        uint64(43690),  // tx_hash[0]
        uint64(48059),  // tx_hash[1]
        uint64(52428),  // tx_hash[2]
        uint64(56797)  // tx_hash[3]
    ];

    function setUp() public {
        verifier = new StarkVerifier();
    }

    function _encodeProof() internal view returns (bytes memory) {
        return vm.parseBytes(vm.readFile("contracts/test/fixtures/stark_proof.hex"));
    }

    // ═══════════════════════════════════════════
    //  Goldilocks Quadratic Extension Tests
    // ═══════════════════════════════════════════

    function test_extMulIdentity() public pure {
        // (1,0) * (a,b) = (a,b)
        (uint256 r0, uint256 r1) = Goldilocks.mulExt(1, 0, 42, 7);
        assertEq(r0, 42);
        assertEq(r1, 7);
    }

    function test_extMulZero() public pure {
        (uint256 r0, uint256 r1) = Goldilocks.mulExt(42, 7, 0, 0);
        assertEq(r0, 0);
        assertEq(r1, 0);
    }

    function test_extMulKnownVector() public pure {
        // From Winterfell test: (3,1) * (4,2) = (8,12)
        (uint256 r0, uint256 r1) = Goldilocks.mulExt(3, 1, 4, 2);
        assertEq(r0, 8);
        assertEq(r1, 12);
    }

    function test_extInvIdentity() public pure {
        // inv(1,0) = (1,0)
        (uint256 r0, uint256 r1) = Goldilocks.invExt(1, 0);
        assertEq(r0, 1);
        assertEq(r1, 0);
    }

    function test_extMulInvCancel() public pure {
        uint256 a0 = 123456789;
        uint256 a1 = 987654321;
        (uint256 inv0, uint256 inv1) = Goldilocks.invExt(a0, a1);
        (uint256 r0, uint256 r1) = Goldilocks.mulExt(a0, a1, inv0, inv1);
        assertEq(r0, 1, "a * inv(a) should be (1,0)");
        assertEq(r1, 0, "a * inv(a) should be (1,0)");
    }

    // ═══════════════════════════════════════════
    //  Fiat-Shamir Transcript Tests
    // ═══════════════════════════════════════════

    function test_initialSeedHash() public pure {
        bytes32 seed = keccak256(abi.encodePacked(
            // 8 context elements (LE u64)
            bytes8(0x0012000000000000), // trace_width=18
            bytes8(0x0800000000000000), // trace_length=8
            bytes8(0x0100000000000000), // 1
            bytes8(0xffffffff00000000), // 4294967295
            bytes8(0x2400000000000000), // num_constraints=36
            bytes8(0x081f080200000000), // 34086664
            bytes8(0x1400000000000000), // 20
            bytes8(0x2c00000000000000), // 44
            // 17 public inputs (LE u64) from the real fixture above
            bytes8(0x57ed70fc3f694b44), // id_com[0] LE
            bytes8(0x6bd28abb756b482c), // id_com[1] LE
            bytes8(0x4b29f09981d77f65), // id_com[2] LE
            bytes8(0xafb6825f25823e55), // id_com[3] LE
            bytes8(0x6ccda53047e32cdf), // target[0] LE
            bytes8(0x65a4ddb18c76b4b7), // target[1] LE
            bytes8(0x7821bebd393eb960), // target[2] LE
            bytes8(0xfa6746dd8a0d5a9c), // target[3] LE
            bytes8(0x5b72aee0833f6ea0), // rp_com[0] LE
            bytes8(0x9415b7d6cb20ee5a), // rp_com[1] LE
            bytes8(0xc12f357d4ad13fd6), // rp_com[2] LE
            bytes8(0xa75eb1857e3eea00), // rp_com[3] LE
            bytes8(0xb1a4000000000000), // domain LE
            bytes8(0xaaaa000000000000), // tx_hash[0] LE
            bytes8(0xbbbb000000000000), // tx_hash[1] LE
            bytes8(0xcccc000000000000), // tx_hash[2] LE
            bytes8(0xdddd000000000000)  // tx_hash[3] LE
        ));
        assertEq(seed, 0x11a7360eb5d77e40f21e8a27301ef8915761700b426a3217924880fae555194c);
    }

    // ═══════════════════════════════════════════
    //  Proof Verification Tests
    // ═══════════════════════════════════════════

    function test_validProofAccepted() public view {
        bytes memory proof = _encodeProof();
        bool result = verifier.verifyProof(proof, pubInputs);
        assertTrue(result, "Valid proof must be accepted");
    }

    function test_invalidPublicInputRejected() public {
        bytes memory proof = _encodeProof();
        uint64[17] memory badInputs = pubInputs;
        badInputs[0] = 0xDEAD; // wrong id_com
        // Changing public inputs changes the Fiat-Shamir seed, which changes
        // the entire transcript. The PoW nonce (valid for the original transcript)
        // is now invalid for the altered transcript → GrindingFailed.
        vm.expectRevert(StarkVerifier.GrindingFailed.selector);
        verifier.verifyProof(proof, badInputs);
    }

    function test_wrongOodDigestRejected() public {
        bytes memory proof = _encodeProof();
        // Tamper with OOD digest (byte 96)
        proof[96] = bytes1(uint8(proof[96]) ^ 0xFF);
        vm.expectRevert(); // OodDigestMismatch
        verifier.verifyProof(proof, pubInputs);
    }

    function test_wrongPowNonceRejected() public {
        bytes memory proof = _encodeProof();
        // Zero out entire PoW nonce region (bytes 128-159)
        for (uint256 i = 128; i < 160; i++) proof[i] = 0x00;
        // Set nonce to 1 (very unlikely to have 20 trailing zeros)
        proof[159] = 0x01;
        vm.expectRevert(); // GrindingFailed
        verifier.verifyProof(proof, pubInputs);
    }

    function test_fieldElementOverflowRejected() public view {
        bytes memory proof = _encodeProof();
        uint64[17] memory badInputs = pubInputs;
        // This won't overflow since uint64 < P for valid elements
        // But P itself is invalid
        badInputs[0] = uint64(P); // P truncated to u64 = 0xFFFFFFFF00000001
        bool result = verifier.verifyProof(proof, badInputs);
        assertFalse(result, "Input >= P should be rejected");
    }

    // ═══════════════════════════════════════════
    //  Merkle Verification Tests
    // ═══════════════════════════════════════════

    function test_merkleVerifyKnownTree() public pure {
        // Build a small Merkle tree manually and verify
        bytes32 leaf0 = keccak256(abi.encodePacked(uint64(1)));
        bytes32 leaf1 = keccak256(abi.encodePacked(uint64(2)));
        bytes32 leaf2 = keccak256(abi.encodePacked(uint64(3)));
        bytes32 leaf3 = keccak256(abi.encodePacked(uint64(4)));

        bytes32 node01 = keccak256(abi.encodePacked(leaf0, leaf1));
        bytes32 node23 = keccak256(abi.encodePacked(leaf2, leaf3));
        bytes32 root = keccak256(abi.encodePacked(node01, node23));

        // Verify leaf0 at position 0
        bytes32[] memory path = new bytes32[](2);
        path[0] = leaf1;
        path[1] = node23;

        // Compute manually
        bytes32 current = leaf0;
        current = keccak256(abi.encodePacked(current, path[0])); // pos 0, left child
        current = keccak256(abi.encodePacked(current, path[1])); // pos 0, left child
        assertEq(current, root, "Merkle path should verify");
    }

    // ═══════════════════════════════════════════
    //  Gas Measurement
    // ═══════════════════════════════════════════

    function test_gasUsage() public {
        bytes memory proof = _encodeProof();
        uint256 gasBefore = gasleft();
        verifier.verifyProof(proof, pubInputs);
        uint256 gasUsed = gasBefore - gasleft();
        emit log_named_uint("STARK verification gas", gasUsed);
        assertTrue(gasUsed < 10_000_000, "Gas should be under 5M");
    }
}
