// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @title IStarkVerifier
/// @notice Interface for the ZK-ACE STARK proof verifier.
///         The STARK proof is generated by the Winterfell prover using:
///         - Keccak256 hash (matches EVM opcode)
///         - Goldilocks field (p = 2^64 - 2^32 + 1)
///         - 18 columns, 8 rows, blowup 8, LDE domain 64
///         - 44 queries, FRI folding factor 8
///         - 128-bit post-quantum security (256-bit Rescue commitments)
interface IStarkVerifier {
    /// @notice Verify a STARK proof for ZK-ACE authorization.
    /// @param proof The serialized STARK proof bytes.
    /// @param publicInputs 17 Goldilocks field elements:
    ///        [0..4]   id_com   — identity commitment (4 elements, 256-bit Rescue digest)
    ///        [4..8]   target   — derivation target (4 elements)
    ///        [8..12]  rp_com   — replay prevention commitment (4 elements)
    ///        [12]     domain   — chain/application domain (1 element)
    ///        [13..17] tx_hash  — transaction hash (4 elements, keccak256 split)
    /// @return True if the proof is valid.
    function verifyProof(
        bytes calldata proof,
        uint64[17] calldata publicInputs
    ) external view returns (bool);
}
